"""add indexes on leads and followups

Revision ID: 0c61520c9265
Revises: 13807a6fdb06
Create Date: 2026-04-01 15:29:10.602624

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c61520c9265'
down_revision: Union[str, Sequence[str], None] = '13807a6fdb06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('followups', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_followups_scheduled_for'), ['scheduled_for'], unique=False)
        batch_op.create_index(batch_op.f('ix_followups_status'), ['status'], unique=False)

    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_leads_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_leads_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_leads_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_leads_thread_id'), ['thread_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_leads_thread_id'))
        batch_op.drop_index(batch_op.f('ix_leads_status'))
        batch_op.drop_index(batch_op.f('ix_leads_created_at'))
        batch_op.drop_index(batch_op.f('ix_leads_category'))

    with op.batch_alter_table('followups', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_followups_status'))
        batch_op.drop_index(batch_op.f('ix_followups_scheduled_for'))

    # ### end Alembic commands ###
